# Generated by Django 5.1.4 on 2024-12-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='intitution_id',
            new_name='institution_id',
        ),
    ]
